input("\t\t We will be collecting your Biodata, please note that your information will be confidential and protected \n\n\t\t Type anything to proceed . . . ")

name = input("----------------------- Fill up the form -----------------------\n\t Name:")
mobile = input("\n\t Mobile No. : ")
email = input("\n\t Email: ")
gender = input("\n\t Gender: ")
guardian = input("\n\t Guardian Name: ")
siblings = input("\n\t Siblings Count: ")
address = input("\n\t Address: ")
birth = input("\n\t Date of Birth: ")
age = input("\n\t Age: ")
education = input("\n\t Education: ")
course = input("\n\t Course Department: ")
marital = input("\n\t Marital Status: ")
religion = input("\n\t Religion: ")
language = input("\n\t Language(s) Known: ")
hobby = input("\n\t Hobbies: ")

print("\n------------------------------- Here's the summary of your form -------------------------------\n\n\t\t" + "It is stated that your name is " + name + ". You can be contacted with this mobile number " + mobile + ". You'll be receiving emails at " + email + ". Your gender is " + gender + ". We can contact your guardian Mr/Ms." +  guardian + ". There are " +  siblings + " of your siblings. You live in " + address + ". Your education level is " +  education + ". You have chosen the course of " +  course + " Department. Your civil status is " +  marital + ". Your religion is " +  religion + ". You know the language(s) of " +  language + ". You like to do some " +  hobby + " as a hobby. " + "\n\n----------------------- Thanks for completing the form! Have a good day! -----------------------\n\t\t")
