def sc1():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("           _____________                           _____________         ||")
    print("            ===========                             ===========            ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                    ==                                     ")
    print("                                             111111                        ")
    print("                                                  1                        ")
    print("                                  e e e          1                         ")
    print("                                e       e       1                          ")
    print("||                              e       e      111111                      ")
    print("||                                e e e                                   +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")
    
def sc2():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("           _____________                           _____________         ||")
    print("            ===========                             ===========            ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                    ==                                     ")
    print("                                              0000000000                   ")
    print("                                                      0                    ")
    print("                                  e e e             0                      ")
    print("                                e       e         0                        ")
    print("||                                e e e          000000000                 ")
    print("||                                                                        +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")

def sc3():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("            eeeee                           eeeee                        ||")
    print("                 eee                     eee                               ")
    print("                    ee                 ee                                  ")
    print("                 eee                     eee                               ")
    print("            eeeee                           eeeee                          ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                      WW      WW      WW                                   ")
    print("||                  WW  WW  WW  WW  WW  WW  WW                             ")
    print("||                WW      WW      WW      WW                              +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")

def sc4():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("                       eeeee                           eeeee             ||")
    print("                            eee                     eee                    ")
    print("                               ee                 ee                       ")
    print("                            eee                     eee                    ")
    print("                       eeeee                           eeeee               ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                 WW      WW      WW                        ")
    print("||                             WW  WW  WW  WW  WW  WW  WW                  ")
    print("||                           WW      WW      WW      WW                   +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")

def sc5():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("            ######################################################         ")
    print("                                                                           ")
    print("           ######################################################          ")
    print("                                                                           ")
    print("            ######################################################         ")
    print("                                                                           ")
    print("           ######################################################          ")
    print("                                                                           ")
    print("            ######################################################         ")
    print("||                                                                         ")
    print("||         ######################################################         +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")

def sc6():
    print("++++                                                             ==========")
    print("++                                                                       ||")
    print("+                                                                        ||")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("                                                                           ")
    print("||                                                                         ")
    print("||                                                                        +")
    print("||                                                                       ++")
    print("==========     type anything to continue...                            ++++")

sc1()