
print("\n=== Welcome to the Biodata Form ===\n")

full_name = input("Full Name: ")
address = input("Address: ")
birth_date = input("Date of Birth (MM/DD/YYYY): ")
birth_place = input("Place of Birth: ")
age = input("Age: ")
gender = input("Gender: ")
civil_status = input("Civil Status: ")
nationality = input("Nationality: ")
religion = input("Religion: ")
weight = input("Weight (in kg): ")
languages = input("Languages Known: ")

print("\n--- Family Information ---")
father_name = input("Father's Name: ")
mother_name = input("Mother's Name: ")

print("\n--- Academic & Contact Information ---")
school_info = input("School/Department, Year & Section: ")
occupation = input("Occupation: ")
email = input("Email Address: ")
mobile = input("Mobile Number: ")

print("\n=========================================================")
print("||                 BIODATA SUMMARY                     ||")
print("=========================================================")
print(f"Name: \t\t\t{full_name}")
print(f"Address:\t\t{address}")
print(f"Date of Birth: \t\t{birth_date}")
print(f"Place: \t\t\t{birth_place}")
print(f"Age: \t\t\t{age}")
print(f"Gender: \t\t{gender}")
print(f"Civil Status: \t\t{civil_status}")
print(f"Nationality: \t\t{nationality}")
print(f"Religion: \t\t{religion}")
print(f"Languages Known: \t{languages}")
print(f"Father's Name: \t\t{father_name}")
print(f"Mother's Name: \t\t{mother_name}")
print(f"School:\t\t\t{school_info}")
print(f"Occupation: \t\t{occupation}")
print(f"Email: \t\t\t{email} | Mobile: {mobile}")
print("=========================================================")
print("\nThank you for completing the Biodata Form!")